services:
    glances:
        image: 'nicolargo/glances:latest'
        tty: true
        stdin_open: true
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - /mnt/user/appdata/glances/glances.conf:/glances/conf/glances.conf
        environment:
          - GLANCES_OPT= "-C /glances/conf/glances.conf -w"
          - TZ= "Americas/Los_Angeles"