services:
  grafana:
    image: grafana/grafana-oss
    user: 99:100
    hostname: grafana
    ports:
      - 3333:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /mnt/user/appdata/grafana:/var/lib/grafana
  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    hostname: influxdb
    volumes:
      - /mnt/user/appdata/influxdb:/var/lib/influxdb2:rw
    #    env_file:
    #      - .env
    #    entrypoint: ["./entrypoint.sh"]
    ports:
      - 8086:8086
    restart: unless-stopped
