services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    hostname: uptime-kuma_host
    volumes:
      - ./mnt/user/appdata/uptimekuma:/app/data1
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped