version: '3.9'
services:
    arch-plexpass:
        image: binhex/arch-plexpass:latest
        environment:
            - PGID=99
            - PUID=100
            - UMASK=000
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=GPU-c4894e0d-ccbb-afe5-9a2e-8e168c343af3
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/mnt/user/appdata/plex:/config'
            - '/mnt/user/media/:/media'
            - '/tmp:/transcode'
        container_name: plex
        network_mode: host
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids:
                            - "0"
                          capabilities: [ gpu ]
                          
    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        hostname: overseerr
        environment:
            PORT: "5055"
            TZ: "America/Los_Angeles"
        ports:
            - 505:5055
        volumes:
            - "/mnt/user/appdata/overseerr/config:/app/config"
        restart: unless-stopped


    # membarr:
    #     image: yoruio/membarr:latest
    #     container_name: membarr
    #     user: "99:100"
    #     hostname: membarr_host
    #     volumes:
    #         - /mnt/user/appdata/membarr:/app/app/config
    #     environment:
    #         - token=${MEMBARR_TOKEN}
    # wizarr:
    #     container_name: wizarr
    #     image: ghcr.io/wizarrrr/wizarr:latest
    #     user: "99:100"
    #     ports:
    #         - 5690:5690
    #     volumes:
    #         - /mnt/user/appdata/wizarr:/data/database
    tautulli:
        image: ghcr.io/tautulli/tautulli
        container_name: tautulli
        restart: unless-stopped
        volumes:
          - /mnt/user/appdata/tautulli:/config
        environment:
            - PUID=99
            - PGID=100
            - TZ=America/Los_Angeles
        ports:
          - 8181:8181