version: '3.3'
services:
  speedtest:
        environment:
            - MODE=standalone
            - ENABLE_ID_OBFUSCATION=true
            - REDACT_IP_ADDRESSES=true
            - DISTANCE=km
            - DISABLE_IPINFO=false
            - TELEMETRY=true
            - PASSWORD="OpenToAll"
        ports:
            - 8887:80
        image: adolfintel/speedtest
        container_name: speedtest
