version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    hostname: memos
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/memos:/var/opt/memos
    ports:
      - 5230:5230