services:
  homarr:
    container_name: homarr-dashboard
    hostname: homarr_host
    image: ghcr.io/ajnart/homarr:dev
    restart: unless-stopped
    volumes:
      - /mnt/disk2/appdata/homarr/config:/app/data/configs
      - /home/jbpixel/Docker/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575
    environment:
      - BASE_URL=homarr.{DOMAIN}
      - PASSWORD=5252
      - PORT=7575
      - TZ=America/Los_Angeles
      - PUID=99
      - PGID=100