services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    hostname: transmission_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=Etc/Los_Angeles
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      - /mnt/user/appdata/transmission:/config
      - /mnt/user/media_cache/downloads:/downloads
      - /mnt/user/media/:/media
      - /mnt/user/appdata/transmission/watch:/watch:ro
      - /mnt/user/media/SHOWS/:/SHOWS
      - /mnt/user/media/ANIME/:/ANIME
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped