services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8888
    volumes:
      - /mnt/user/appdata/qbittorrent/config:/config
      # - /mnt/user/appdata/qbittorrent/downloads:/downloads
      - /mnt/user/media_cache/downloads:/downloads
      - /mnt/user/media/:/media
    ports:
      - 8888:8888
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
