version: "3"
services:
    Sonarr:
      container_name: Sonarr
      hostname: sonarr_host
      image: linuxserver/sonarr:latest
      restart: unless-stopped
      volumes:
        - /mnt/user/appdata/sonarr:/config
        - /mnt/user/media/SHOWS:/SHOWS
        - /mnt/user/media/ANIME:/ANIME
        - /mnt/user/media_cache/downloads:/downloads
      environment:
        - PUID=99
        - PGID=100
        - TZ=America/Los_Angeles
      ports:  
        - 8990:8989
