services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr_host
    tty:  true
    stdin_open: true
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/media/:/media
      - /mnt/user/media/MOVIES/:/movies
      - /mnt/user/media_cache/downloads:/downloads
    restart: unless-stopped
    ports:
      - 7878:7878
