version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.1.121:53:53/tcp"
      - "192.168.1.121:53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "192.168.1.121:86:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: 'foobar123'
      DNSSEC: "true"
    # Volumes store your data between container upgrades
    volumes:
      - '/mnt/user/appdata/pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped