services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/lidarr:/config
      - /mnt/user/media/MUSIC:/music
      - /mnt/user/media_cache/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped