services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    tty: true
    stdin_open: true
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/media/:/media
      - /mnt/user/media/MOVIES/:/movies
      - /mnt/user/media_cache/downloads:/downloads
    restart: unless-stopped
    ports:
      - 7878:7878
    networks: [arr_network]
  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/media/SHOWS:/SHOWS
      - /mnt/user/media/ANIME:/ANIME
      - /mnt/user/media_cache/downloads:/downloads
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    ports:
      - 8990:8989
    networks: [arr_network]

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/bazarr/config:/config
      - /mnt/user/media/MOVIES/:/movies #optional
      - /mnt/user/media/SHOWS/:/tv #optional
    ports:
      - 6767:6767
    networks: [arr_network]
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    ports:
      - 9696:9696
    networks: [arr_network]
    restart: unless-stopped
  flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - PUID=99
      - PGID=100
    ports:
      - "8191:8191"
    networks: [arr_network]

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    hostname: recyclarr
    user: 99:100
    networks: [arr_network]
    volumes:
      - /mnt/user/appdata/recyclarr:/config
    environment:
      - TZ=America/Los_Angeles
      - RECYLARR_CREATE_CONFIG=true

  networks:
    arr:
      name: arr_network
      external: true
