services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/user/media:/media
    # ports:
    #   - 8123:8123 #optional
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.13.1-tensorrt
    shm_size: "160mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/frigate/config.yml:/config/config.yml
      - /mnt/user/recordings:/media/frigate
      - /mnt/user/appdata/frigate/trt-models/trt-models/:/trt-models/
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5500:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    restart: unless-stopped
    deploy: 
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "1"
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    hostname: mosquitto_host
    volumes:
      - /mnt/user/appdata/mosquitto/config:/mosquitto/config/
      - /mnt/user/appdata/mosquitto/log/:/mosquitto/log/
      - /mnt/user/appdata/mosquitto/data/:/mosquitto/data/
    ports:
      - 1883:1883
      - 9901:9001

  # wyoming-piper:
  #   command: "--voice en_US-lessac-medium"
  #   image: rhasspy/wyoming-piper:latest
  #   volumes:
  #     - "/mnt/user/appdata/piper/:/data"
  #   ports:
  #     - "10200:10200"
  #   tty: true
  #   stdin_open: true

