version: "3.9"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/user/media:/media
    # ports:
    #   - 8123:8123 #optional
    restart: unless-stopped

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.12.0-tensorrt
    shm_size: "1024mb" # update for your cameras based on calculation above
    #devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/frigate/config.yml:/config/config.yml
      - /mnt/user/recordings:/media/frigate
      - /mnt/user/appdata/frigate/trt-models/:/trt-models/

      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5500:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"      
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    hostname: mosquitto_host
    volumes:
      - /mnt/user/appdata/mosquitto/config:/mosquitto/config/
      - /mnt/user/appdata/mosquitto/log/:/mosquitto/log/
      - /mnt/user/appdata/mosquitto/data/:/mosquitto/data/
    ports:
      - 1883:1883
      - 9901:9001
  # go2rtc:
  #     image: alexxit/go2rtc
  #     container_name: go2rtc
  #     network_mode: host       # important for WebRTC, HomeKit, UDP cameras
  #     privileged: true         # only for FFmpeg hardware transcoding
  #     restart: unless-stopped  # autorestart on fail or config change from WebUI
  #     ports:
  #       - 1984:1984 #api port
  #       - 8554:8554 #rstp port
  #       - 8555:8555 #tcp/udp port
          
  #     environment:
  #       - TZ=America/Los_Angeles  # timezone in logs
  #     volumes:
  #       - /mnt/user/appdata/go2rtc:/config
